# Generated by Django 3.0.7 on 2020-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название организации')),
                ('description', models.TextField(verbose_name='О компании')),
                ('adress', models.CharField(max_length=200, verbose_name='Адрес организации')),
                ('director', models.CharField(max_length=200, verbose_name='Директор организации')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('video', models.FileField(upload_to='filesInput/')),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
